### ISSUE TITLE
Import from an RDG file does not import anything from the file

### ISSUE THREAD

**Issue by peterbax117** [Terminals-Origin/Terminals#75]
When I try to import from an RDG file, the Organize Favorites window just returns with no additional values and no errors.  This is version 4.0.1

**Comment by jirkapok** [comment]
Can you provide related RDG file?

**Comment by JbRbV** [comment]
When I import a RDG from RDCM 2.7 file, the Organize Favorites just returns with no additional values and no errors. This is version 4.0.1 and a RDG 2,7 file
[CWR.zip](https://github.com/Terminals-Origin/Terminals/files/1290664/CWR.zip)

**Comment by cewjr9842** [comment]
I am having the same issue when trying to import from Remote Desktop manager. It does not come back with of my connections. I mange about 200 Servers, any help would surely help!

**Comment by thylocene** [comment]
The issue is that the lates version of terminals only supports the schema for programVersion 2.2 of RDG

**Comment by cewjr9842** [comment]
Was this ever addressed in regards to the versioning of remote desktop manager?
Are we able to import from the newer version of RDM to Terminals as of yet? Terminals rocks and i hate to have to setup 600 servers.

**Comment by jirkapok** [comment]
No one tried yet. We have example files, the issues is obvious, but it is not fixed yet.
